// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: exercise/exercise.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Exercise struct {
	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address   string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Category  string `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Score     uint64 `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	StartTime int64  `protobuf:"varint,5,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime   int64  `protobuf:"varint,6,opt,name=endTime,proto3" json:"endTime,omitempty"`
	CreatedAt int64  `protobuf:"varint,7,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
}

func (m *Exercise) Reset()         { *m = Exercise{} }
func (m *Exercise) String() string { return proto.CompactTextString(m) }
func (*Exercise) ProtoMessage()    {}
func (*Exercise) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e9306b74e5989d7, []int{0}
}
func (m *Exercise) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Exercise) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Exercise.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Exercise) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exercise.Merge(m, src)
}
func (m *Exercise) XXX_Size() int {
	return m.Size()
}
func (m *Exercise) XXX_DiscardUnknown() {
	xxx_messageInfo_Exercise.DiscardUnknown(m)
}

var xxx_messageInfo_Exercise proto.InternalMessageInfo

func (m *Exercise) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Exercise) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Exercise) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Exercise) GetScore() uint64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Exercise) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Exercise) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *Exercise) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*Exercise)(nil), "hackatomopctchain.exercise.Exercise")
}

func init() { proto.RegisterFile("exercise/exercise.proto", fileDescriptor_8e9306b74e5989d7) }

var fileDescriptor_8e9306b74e5989d7 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x3f, 0x4e, 0xc3, 0x30,
	0x18, 0xc5, 0xf3, 0xa5, 0xff, 0x3d, 0x30, 0x58, 0x48, 0x58, 0x15, 0xb2, 0x22, 0xc4, 0x90, 0xa5,
	0xcd, 0xc0, 0x8e, 0x04, 0x88, 0x0b, 0x44, 0x4c, 0x6c, 0xc6, 0xfe, 0x44, 0x2d, 0xd4, 0x3a, 0xb2,
	0xbf, 0xa1, 0xbd, 0x05, 0x07, 0xe2, 0x00, 0x8c, 0x1d, 0x19, 0x51, 0x72, 0x11, 0x14, 0x17, 0xa7,
	0x9b, 0x7f, 0xef, 0xf9, 0xd9, 0x7a, 0x8f, 0x5d, 0xe1, 0x1e, 0xbd, 0xb6, 0x01, 0xab, 0x74, 0x58,
	0x37, 0xde, 0x91, 0xe3, 0xcb, 0x8d, 0xd2, 0x1f, 0x8a, 0xdc, 0xd6, 0x35, 0x9a, 0xf4, 0x46, 0xd9,
	0xdd, 0x3a, 0xdd, 0xb8, 0xf9, 0x02, 0x36, 0x7f, 0xfe, 0x07, 0x7e, 0xc1, 0x72, 0x6b, 0x04, 0x14,
	0x50, 0x8e, 0xeb, 0xdc, 0x1a, 0x2e, 0xd8, 0x4c, 0x19, 0xe3, 0x31, 0x04, 0x91, 0x17, 0x50, 0x2e,
	0xea, 0x84, 0x7c, 0xc9, 0xe6, 0x5a, 0x11, 0xbe, 0x3b, 0x7f, 0x10, 0xa3, 0x68, 0x0d, 0xcc, 0x2f,
	0xd9, 0x24, 0x68, 0xe7, 0x51, 0x8c, 0xe3, 0x43, 0x27, 0xe0, 0xd7, 0x6c, 0x11, 0x48, 0x79, 0x7a,
	0xb1, 0x5b, 0x14, 0x93, 0x02, 0xca, 0x51, 0x7d, 0x16, 0xfa, 0x9f, 0x70, 0x67, 0xa2, 0x37, 0x8d,
	0x5e, 0xc2, 0x3e, 0xf7, 0xe4, 0x51, 0x11, 0x9a, 0x07, 0x12, 0xb3, 0x53, 0x6e, 0x10, 0x1e, 0xef,
	0xbf, 0x5b, 0x09, 0xc7, 0x56, 0xc2, 0x6f, 0x2b, 0xe1, 0xb3, 0x93, 0xd9, 0xb1, 0x93, 0xd9, 0x4f,
	0x27, 0xb3, 0xd7, 0xdb, 0x54, 0x7a, 0xd5, 0xb7, 0x5e, 0xc5, 0xda, 0xd5, 0x7e, 0x98, 0xa6, 0xa2,
	0x43, 0x83, 0xe1, 0x6d, 0x1a, 0x17, 0xba, 0xfb, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x43, 0x37, 0x81,
	0x33, 0x3c, 0x01, 0x00, 0x00,
}

func (m *Exercise) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Exercise) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Exercise) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreatedAt != 0 {
		i = encodeVarintExercise(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x38
	}
	if m.EndTime != 0 {
		i = encodeVarintExercise(dAtA, i, uint64(m.EndTime))
		i--
		dAtA[i] = 0x30
	}
	if m.StartTime != 0 {
		i = encodeVarintExercise(dAtA, i, uint64(m.StartTime))
		i--
		dAtA[i] = 0x28
	}
	if m.Score != 0 {
		i = encodeVarintExercise(dAtA, i, uint64(m.Score))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Category) > 0 {
		i -= len(m.Category)
		copy(dAtA[i:], m.Category)
		i = encodeVarintExercise(dAtA, i, uint64(len(m.Category)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintExercise(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintExercise(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintExercise(dAtA []byte, offset int, v uint64) int {
	offset -= sovExercise(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Exercise) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovExercise(uint64(m.Id))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovExercise(uint64(l))
	}
	l = len(m.Category)
	if l > 0 {
		n += 1 + l + sovExercise(uint64(l))
	}
	if m.Score != 0 {
		n += 1 + sovExercise(uint64(m.Score))
	}
	if m.StartTime != 0 {
		n += 1 + sovExercise(uint64(m.StartTime))
	}
	if m.EndTime != 0 {
		n += 1 + sovExercise(uint64(m.EndTime))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovExercise(uint64(m.CreatedAt))
	}
	return n
}

func sovExercise(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozExercise(x uint64) (n int) {
	return sovExercise(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Exercise) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowExercise
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Exercise: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Exercise: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExercise
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExercise
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExercise
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExercise
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Category", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExercise
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExercise
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExercise
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Category = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Score", wireType)
			}
			m.Score = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExercise
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Score |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			m.StartTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExercise
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			m.EndTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExercise
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExercise
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipExercise(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthExercise
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipExercise(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowExercise
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowExercise
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowExercise
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthExercise
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupExercise
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthExercise
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthExercise        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowExercise          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupExercise = fmt.Errorf("proto: unexpected end of group")
)
