// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hackatomopctchain/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgDoneOpct struct {
	Creator     string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Category    string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Score       int32  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Starttime   int64  `protobuf:"varint,4,opt,name=starttime,proto3" json:"starttime,omitempty"`
	Endtime     int64  `protobuf:"varint,5,opt,name=endtime,proto3" json:"endtime,omitempty"`
	Challengeid uint64 `protobuf:"varint,6,opt,name=challengeid,proto3" json:"challengeid,omitempty"`
}

func (m *MsgDoneOpct) Reset()         { *m = MsgDoneOpct{} }
func (m *MsgDoneOpct) String() string { return proto.CompactTextString(m) }
func (*MsgDoneOpct) ProtoMessage()    {}
func (*MsgDoneOpct) Descriptor() ([]byte, []int) {
	return fileDescriptor_e31f952edeb77638, []int{0}
}
func (m *MsgDoneOpct) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDoneOpct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDoneOpct.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDoneOpct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDoneOpct.Merge(m, src)
}
func (m *MsgDoneOpct) XXX_Size() int {
	return m.Size()
}
func (m *MsgDoneOpct) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDoneOpct.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDoneOpct proto.InternalMessageInfo

func (m *MsgDoneOpct) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDoneOpct) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *MsgDoneOpct) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *MsgDoneOpct) GetStarttime() int64 {
	if m != nil {
		return m.Starttime
	}
	return 0
}

func (m *MsgDoneOpct) GetEndtime() int64 {
	if m != nil {
		return m.Endtime
	}
	return 0
}

func (m *MsgDoneOpct) GetChallengeid() uint64 {
	if m != nil {
		return m.Challengeid
	}
	return 0
}

type MsgDoneOpctResponse struct {
}

func (m *MsgDoneOpctResponse) Reset()         { *m = MsgDoneOpctResponse{} }
func (m *MsgDoneOpctResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDoneOpctResponse) ProtoMessage()    {}
func (*MsgDoneOpctResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e31f952edeb77638, []int{1}
}
func (m *MsgDoneOpctResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDoneOpctResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDoneOpctResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDoneOpctResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDoneOpctResponse.Merge(m, src)
}
func (m *MsgDoneOpctResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDoneOpctResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDoneOpctResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDoneOpctResponse proto.InternalMessageInfo

type MsgCreateChallenge struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Category string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Date     int64  `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	Uri      string `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
}

func (m *MsgCreateChallenge) Reset()         { *m = MsgCreateChallenge{} }
func (m *MsgCreateChallenge) String() string { return proto.CompactTextString(m) }
func (*MsgCreateChallenge) ProtoMessage()    {}
func (*MsgCreateChallenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_e31f952edeb77638, []int{2}
}
func (m *MsgCreateChallenge) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateChallenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateChallenge.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateChallenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateChallenge.Merge(m, src)
}
func (m *MsgCreateChallenge) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateChallenge) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateChallenge.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateChallenge proto.InternalMessageInfo

func (m *MsgCreateChallenge) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateChallenge) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *MsgCreateChallenge) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *MsgCreateChallenge) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

type MsgCreateChallengeResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreateChallengeResponse) Reset()         { *m = MsgCreateChallengeResponse{} }
func (m *MsgCreateChallengeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateChallengeResponse) ProtoMessage()    {}
func (*MsgCreateChallengeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e31f952edeb77638, []int{3}
}
func (m *MsgCreateChallengeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateChallengeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateChallengeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateChallengeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateChallengeResponse.Merge(m, src)
}
func (m *MsgCreateChallengeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateChallengeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateChallengeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateChallengeResponse proto.InternalMessageInfo

func (m *MsgCreateChallengeResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgDoneOpct)(nil), "hackatomopctchain.hackatomopctchain.MsgDoneOpct")
	proto.RegisterType((*MsgDoneOpctResponse)(nil), "hackatomopctchain.hackatomopctchain.MsgDoneOpctResponse")
	proto.RegisterType((*MsgCreateChallenge)(nil), "hackatomopctchain.hackatomopctchain.MsgCreateChallenge")
	proto.RegisterType((*MsgCreateChallengeResponse)(nil), "hackatomopctchain.hackatomopctchain.MsgCreateChallengeResponse")
}

func init() { proto.RegisterFile("hackatomopctchain/tx.proto", fileDescriptor_e31f952edeb77638) }

var fileDescriptor_e31f952edeb77638 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xc1, 0x4e, 0xf2, 0x40,
	0x10, 0x66, 0xdb, 0xc2, 0x0f, 0x43, 0xf2, 0xff, 0x7f, 0x56, 0x4d, 0x9a, 0xc6, 0x34, 0x4d, 0xbd,
	0xf4, 0x20, 0xc5, 0xe8, 0x41, 0x6f, 0x26, 0x62, 0xe2, 0x89, 0x98, 0xec, 0xd1, 0xdb, 0xba, 0xdd,
	0x94, 0x46, 0xe8, 0x36, 0xbb, 0xab, 0x81, 0x67, 0xe0, 0xe2, 0xbb, 0xf8, 0x12, 0x1e, 0x39, 0x7a,
	0x34, 0xf0, 0x22, 0xa6, 0x4b, 0x8a, 0x04, 0x3c, 0x20, 0xb7, 0xf9, 0xe6, 0xdb, 0x99, 0xf9, 0xbe,
	0xd9, 0x01, 0x6f, 0x40, 0xd9, 0x13, 0xd5, 0x62, 0x24, 0x0a, 0xa6, 0xd9, 0x80, 0x66, 0x79, 0x57,
	0x8f, 0xe3, 0x42, 0x0a, 0x2d, 0xf0, 0xc9, 0x16, 0x17, 0x6f, 0x65, 0xc2, 0x37, 0x04, 0xed, 0xbe,
	0x4a, 0x6f, 0x45, 0xce, 0xef, 0x0b, 0xa6, 0xb1, 0x0b, 0x7f, 0x98, 0xe4, 0x54, 0x0b, 0xe9, 0xa2,
	0x00, 0x45, 0x2d, 0x52, 0x41, 0xec, 0x41, 0x93, 0x51, 0xcd, 0x53, 0x21, 0x27, 0xae, 0x65, 0xa8,
	0x15, 0xc6, 0x87, 0x50, 0x57, 0x4c, 0x48, 0xee, 0xda, 0x01, 0x8a, 0xea, 0x64, 0x09, 0xf0, 0x31,
	0xb4, 0x94, 0xa6, 0x52, 0xeb, 0x6c, 0xc4, 0x5d, 0x27, 0x40, 0x91, 0x4d, 0xbe, 0x13, 0xe5, 0x24,
	0x9e, 0x27, 0x86, 0xab, 0x1b, 0xae, 0x82, 0x38, 0x80, 0x36, 0x1b, 0xd0, 0xe1, 0x90, 0xe7, 0x29,
	0xcf, 0x12, 0xb7, 0x11, 0xa0, 0xc8, 0x21, 0xeb, 0xa9, 0xf0, 0x08, 0x0e, 0xd6, 0x44, 0x13, 0xae,
	0x0a, 0x91, 0x2b, 0x1e, 0x16, 0x80, 0xfb, 0x2a, 0xed, 0x95, 0x82, 0x79, 0xaf, 0x7a, 0xbe, 0xa7,
	0x25, 0x0c, 0x4e, 0x42, 0xf5, 0xd2, 0x91, 0x4d, 0x4c, 0x8c, 0xff, 0x83, 0xfd, 0x2c, 0x33, 0x63,
	0xa5, 0x45, 0xca, 0x30, 0x3c, 0x05, 0x6f, 0x7b, 0x62, 0xa5, 0x07, 0xff, 0x05, 0x2b, 0x4b, 0xcc,
	0x50, 0x87, 0x58, 0x59, 0x72, 0x3e, 0xb5, 0xc0, 0xee, 0xab, 0x14, 0xbf, 0x40, 0x73, 0xb5, 0xf0,
	0xb3, 0x78, 0x87, 0x6f, 0x8a, 0xd7, 0xdc, 0x7a, 0x57, 0xbf, 0xad, 0x58, 0xe9, 0x99, 0x22, 0xf8,
	0xb7, 0xb9, 0x9d, 0xcb, 0x5d, 0xbb, 0x6d, 0x14, 0x7a, 0xd7, 0x7b, 0x16, 0x56, 0x6a, 0x6e, 0xee,
	0xde, 0xe7, 0x3e, 0x9a, 0xcd, 0x7d, 0xf4, 0x39, 0xf7, 0xd1, 0xeb, 0xc2, 0xaf, 0xcd, 0x16, 0x7e,
	0xed, 0x63, 0xe1, 0xd7, 0x1e, 0x3a, 0x55, 0x9f, 0x4e, 0xd9, 0xa8, 0xb3, 0xbc, 0xeb, 0x71, 0xf7,
	0x87, 0x5b, 0x9f, 0x14, 0x5c, 0x3d, 0x36, 0xcc, 0xbd, 0x5f, 0x7c, 0x05, 0x00, 0x00, 0xff, 0xff,
	0x15, 0xde, 0xef, 0xb0, 0x0d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	DoneOpct(ctx context.Context, in *MsgDoneOpct, opts ...grpc.CallOption) (*MsgDoneOpctResponse, error)
	CreateChallenge(ctx context.Context, in *MsgCreateChallenge, opts ...grpc.CallOption) (*MsgCreateChallengeResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) DoneOpct(ctx context.Context, in *MsgDoneOpct, opts ...grpc.CallOption) (*MsgDoneOpctResponse, error) {
	out := new(MsgDoneOpctResponse)
	err := c.cc.Invoke(ctx, "/hackatomopctchain.hackatomopctchain.Msg/DoneOpct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateChallenge(ctx context.Context, in *MsgCreateChallenge, opts ...grpc.CallOption) (*MsgCreateChallengeResponse, error) {
	out := new(MsgCreateChallengeResponse)
	err := c.cc.Invoke(ctx, "/hackatomopctchain.hackatomopctchain.Msg/CreateChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	DoneOpct(context.Context, *MsgDoneOpct) (*MsgDoneOpctResponse, error)
	CreateChallenge(context.Context, *MsgCreateChallenge) (*MsgCreateChallengeResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) DoneOpct(ctx context.Context, req *MsgDoneOpct) (*MsgDoneOpctResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoneOpct not implemented")
}
func (*UnimplementedMsgServer) CreateChallenge(ctx context.Context, req *MsgCreateChallenge) (*MsgCreateChallengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChallenge not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_DoneOpct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDoneOpct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DoneOpct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hackatomopctchain.hackatomopctchain.Msg/DoneOpct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DoneOpct(ctx, req.(*MsgDoneOpct))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateChallenge)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hackatomopctchain.hackatomopctchain.Msg/CreateChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateChallenge(ctx, req.(*MsgCreateChallenge))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hackatomopctchain.hackatomopctchain.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoneOpct",
			Handler:    _Msg_DoneOpct_Handler,
		},
		{
			MethodName: "CreateChallenge",
			Handler:    _Msg_CreateChallenge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hackatomopctchain/tx.proto",
}

func (m *MsgDoneOpct) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDoneOpct) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDoneOpct) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Challengeid != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Challengeid))
		i--
		dAtA[i] = 0x30
	}
	if m.Endtime != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Endtime))
		i--
		dAtA[i] = 0x28
	}
	if m.Starttime != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Starttime))
		i--
		dAtA[i] = 0x20
	}
	if m.Score != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Score))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Category) > 0 {
		i -= len(m.Category)
		copy(dAtA[i:], m.Category)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Category)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDoneOpctResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDoneOpctResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDoneOpctResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateChallenge) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateChallenge) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateChallenge) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Uri) > 0 {
		i -= len(m.Uri)
		copy(dAtA[i:], m.Uri)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Uri)))
		i--
		dAtA[i] = 0x22
	}
	if m.Date != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Date))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Category) > 0 {
		i -= len(m.Category)
		copy(dAtA[i:], m.Category)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Category)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateChallengeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateChallengeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateChallengeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgDoneOpct) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Category)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Score != 0 {
		n += 1 + sovTx(uint64(m.Score))
	}
	if m.Starttime != 0 {
		n += 1 + sovTx(uint64(m.Starttime))
	}
	if m.Endtime != 0 {
		n += 1 + sovTx(uint64(m.Endtime))
	}
	if m.Challengeid != 0 {
		n += 1 + sovTx(uint64(m.Challengeid))
	}
	return n
}

func (m *MsgDoneOpctResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateChallenge) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Category)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Date != 0 {
		n += 1 + sovTx(uint64(m.Date))
	}
	l = len(m.Uri)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateChallengeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgDoneOpct) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDoneOpct: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDoneOpct: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Category", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Category = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Score", wireType)
			}
			m.Score = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Score |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Starttime", wireType)
			}
			m.Starttime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Starttime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Endtime", wireType)
			}
			m.Endtime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Endtime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Challengeid", wireType)
			}
			m.Challengeid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Challengeid |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDoneOpctResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDoneOpctResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDoneOpctResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateChallenge) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateChallenge: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateChallenge: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Category", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Category = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Date", wireType)
			}
			m.Date = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Date |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateChallengeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateChallengeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateChallengeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
